### ISSUE TITLE
Support MulAdd and MulAddAssign for no_std

### ISSUE THREAD

**Issue by Schultzer** [rust-num/num-traits#102]
Is MulAdd and MulAddAssign supported for no_std?

I looked at the docs for for [f64](https://doc.rust-lang.org/std/primitive.f64.html#method.mul_add) and as far as I understand there shouldn't be any problem in making these traits no_std.

Looking at the code for [mul_add](https://github.com/rust-num/num-traits/blob/master/src/ops/mul_add.rs) it looks like only std is supported?

https://doc.rust-lang.org/core/intrinsics/fn.fmaf32.html
https://doc.rust-lang.org/core/intrinsics/fn.fmaf64.html

**Comment by cuviper** [comment]
The `core` [`impl f64`](https://github.com/rust-lang/rust/blob/55c173c8ae8bda689fd609f391ee5e2e5b1b6d44/src/libcore/num/f64.rs#L146) does not include ` mul_add`, nor anything else based on intrinsics. We can't call the intrinsics directly because they are marked unstable, for use only with nightly versions of rustc. So while the `MulAdd` traits do exist under `no_std`, we don't have a way to implement them for floats.

I think `core` doesn't use intrinsics because LLVM may lower them to external calls on some targets.

**Comment by Schultzer** [comment]
I guess this can only be done with `libm` with the [F32Ext](https://github.com/rust-lang-nursery/libm/blob/3559e703795d33e84a91da2a35f2f3baac47e872/src/lib.rs#L184) and [F64Ext](https://github.com/rust-lang-nursery/libm/blob/3559e703795d33e84a91da2a35f2f3baac47e872/src/lib.rs#L361)

**Comment by cuviper** [comment]
Oh, #99 actually does include this!

**Comment by cuviper** [comment]
The libm feature is now supported in 2.0.9.
