### ISSUE TITLE
A trait to require ops on references

### ISSUE THREAD

**Issue by vandenheuvel** [rust-num/num-traits#170]
I noticed e.g. [this implementation](https://docs.rs/num-bigint/0.2.6/src/num_bigint/bigint.rs.html#944) to implement numerical operations on references, in this case `impl<'a, 'b> Add<&'b BigInt> for &'a BigInt`. Is there a trait that allows one to require that such implementations on references exist? E.g. something like below:
```rust
trait OpsOnBothValueAndRefs: NumOps<Self> + for<'r, 's> &'r Self: NumOps<'s Self> {}
```

**Comment by cuviper** [comment]
There are a few supertraits you can choose in various combinations of `NumOps`:

- [`Num`](https://docs.rs/num-traits/0.2.11/num_traits/trait.Num.html) is `NumOps` and a few other traits, plus a `from_str_radix` method.
- [`NumRef`](https://docs.rs/num-traits/0.2.11/num_traits/trait.NumRef.html) is `Num + for<'r> NumOps<&'r Self>`, basically adding a reference RHS.
- [`RefNum<Base>`](https://docs.rs/num-traits/0.2.11/num_traits/trait.RefNum.html) is trait that would be implemented for `&Base`, requiring `NumOps<Base, Base> + for<'r> NumOps<&'r Base, Base>` -- i.e. reference LHS, reference or value RHS.

So you could write the full combination something like this:

```rust
trait OpsOnBothValueAndRefs: NumRef
where
    for<'r> &'r Self: RefNum<Self>,
{}
```

However, https://github.com/rust-lang/rust/issues/20671 is the reason such a trait isn't already provided. Since the extra `where` clause isn't elaborated, everywhere you write `T: OpsOnBothValueAndRefs`, you would also have to repeat the `for<'r> &'r T: RefNum<T>`, which loses a lot of the value of a combined trait in the first place.

**Comment by vandenheuvel** [comment]
That explains a lot. Thank you very much!

As a follow-up: how is decided, which traits on references to implement? For example, I notice that there is a `impl<'a, T> Add<Ratio<T>> for &'a Ratio<T>` but no `impl<'a, T> PartialEq<Ratio<T>> for &'a Ratio<T>`.

Are they just added as needed? Could I potentially make a pull request with an impl for such a missing implementation if that would be convenient for my use case?
