### ISSUE TITLE
Feature Request: Impl AsPrimitive for NonZero

### ISSUE THREAD

**Issue by foolishell** [rust-num/num-traits#335]
# Background

I use async-graphql which depends on this crate on validation.
https://github.com/async-graphql/async-graphql/blob/master/src/validators/minimum.rs

I want to use NonZero Integers as well as normal integers.

# Feature Request

impl AsPrimitive for NonZero integers

**Comment by cuviper** [comment]
> I use async-graphql which depends on this crate on validation.
> https://github.com/async-graphql/async-graphql/blob/master/src/validators/minimum.rs

Given that `AsPrimitive` is lossy, I think it's quite dangerous to use for validation, even aside from `NonZero`. For example, `minimum(&-1, 032)` will return `Ok`!

**Comment by cuviper** [comment]
Use-case aside -- we aren't currently implementing this for any non-primitive types, as I mentioned in <https://github.com/rust-num/num-traits/pull/334#issuecomment-2357065696>. That's not necessarily a show-stopper, since the trait docs do mention newtypes too, but it would be an expansion from what we have now.

**Comment by foolishell** [comment]
Thank you for telling me!
I'll close this issue.
