### ISSUE TITLE
Feature request: Recip trait

### ISSUE THREAD

**Issue by clarcharr** [rust-num/num-traits#34]
Essentially, a pair to `Neg` for multiplication. Anything which can have its reciprocal taken would implement this. Useful in the context of `Mul + Recip + One`, for example.

**Comment by cuviper** [comment]
Sure, I could see this applicable to floating point, `Complex`, and `Ratio` at least.

It may also be useful for stuff like modular arithmetic and square matrices, although it would more often be called an "inverse" in those settings.  Those may also want more control of failure modes, since it's not as simple as division by zero -- maybe with `try`/`checked` variants?

**Comment by clarcharr** [comment]
@cuviper I agree, and while `Inv` might be a better name, `recip` is already used for most numbers and may be best. Also, even though "reciprocal matrix" is weird to say, it's not unheard of.
