### ISSUE TITLE
More features for `Float`

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-traits#8]
_From @bluss on March 7, 2016 15:19_

If `Float` truly is for `f32` and `f64` (it should be), we can frontload it with as much features as possible.

Wishlist:
- `'static`
- `Display + Debug + LowerExp + UpperExp`
- Send + Sync

_Copied from original issue: rust-num/num#178_

**Comment by cuviper** [comment]
_From @AtheMathmo on November 1, 2016 9:13_

Oh neat, thanks!

**Comment by cuviper** [comment]
I've decided to limit the clutter of `breaking change` issues, so they will now be tracked collectively in #47.  I'm closing this issue for now as `postponed` but we can still discuss its merits here as needed.

**Comment by bluenote10** [comment]
What is that status of this issue?

I'm trying to fix bugs in a library that uses the `Float` trait everywhere, and because `Debug` and `Display` are missing debugging is quite painful (requires to propagate `Debug` manually basically through the entire code base).

**Comment by cuviper** [comment]
No change.

If you need to propagate it widely, if suggest making your own combined trait:

```rust
trait MyFloat: Float + Debug {}
impl<T: Float + Debug> MyFloat for T {}
```

Maybe we could add some extended trait like this to `num_traits`, without changing `Float` itself.

**Comment by bluenote10** [comment]
> If you need to propagate it widely, I'd suggest making your own combined trait:

Not so easy, I'm not the library owner and can't make the decision. Currently I'm editing all the files every time I start debugging, just to remove all the edits before opening PRs...

> Maybe we could add some extended trait ...

That would be nice. On the other hand, are you aware of implementations of `Float` that don't implement `Display` and `Debug`? I'd guess that >99% of the use cases are `f32` and `f64` for which it wouldn't be a breaking change. If `Float` stays inconvenient, I'm most likely not the last developer losing time due to not being able to quickly debug print something, which feels like a harsh punishment of writing generic code ;).

**Comment by cuviper** [comment]
> I'd guess that >99% of the use cases are `f32` and `f64` for which it wouldn't be a breaking change.

Maybe so, but I'd rather not make guesses when it comes to breaking changes.

If you're able to use a nightly toolchain for debugging, the [`debugit`](https://crates.io/crates/debugit) crate mentioned above or the newer [`dbg`](https://crates.io/crates/dbg) crate both allow debug-printing without a `Debug` trait bound using specialization (which is why they need nightly).
