### ISSUE TITLE
Feature request: 'One' and 'Zero' traits for bool

### ISSUE THREAD

**Issue by tsoernes** [rust-num/num-traits#84]
Could we get the One and Zero traits implemented for booleans, as true and false respectively? It would be useful, for example, in the context or `ndarray` where arrays often are initialized using either trait, e.g. `let arr: Array1<usize> = Array::zeroes(5)` which in turn uses the Zero trait for usize. I would like to be able to do the same with booleans.

Thank you

**Comment by hauleth** [comment]
I think it would be better for you to define:

```rust
struct Bit(bool);

trait Zero for Bit {
    fn zero() -> Self { Bit(false) }
}

trait One for Bit {
    fn one() -> Self { Bit(true) }
}
```

Thanks to that it will:

- be more descriptive what value is doing
- it will be easier to implement other traits

Also for "zeroed" booleans you already have `Array::default(5)`.

**Comment by cuviper** [comment]
I'm a little sympathetic now that integers have `From<bool>`, since Rust 1.28, so it makes a little sense to treat `bool` numerically.  But we'll still be blocked on the `Zero: Add` and `One: Mul` requirements, because `bool` doesn't implement those operators.

In addition to `Array::default`, you can use `Array::from_elem` for either `true` or `false` as you like.

**Comment by cuviper** [comment]
We can't implement `core` traits on `bool` from here.
